// ════════════════════════════════════════════════════════════════════
//  ICÔNES DU GRIMOIRE (27/09) — GÉNÉRÉ par script, ne pas éditer à la main
// ════════════════════════════════════════════════════════════════════
// 6 planches Gemini de 9 icônes (prompts 62-67), découpées par cellules ;
// chaque icône est associée à son élément par NOM EXACT dans les données
// (les identifiants internes ne ressemblent pas toujours aux noms :
// « griffeBrais » = Griffe de Pyrosile, « titanfoudre » = Héraut d'Orage).
// Clé = identifiant du modèle des éléments (reliques : « relique:<id> »).
/* eslint-disable */
export const ICONES = {
  'automate': require('../../../assets/grimoire/icones/automate.png'),
  'colonie': require('../../../assets/grimoire/icones/colonie.png'),
  'colosse': require('../../../assets/grimoire/icones/colosse.png'),
  'critDamage': require('../../../assets/grimoire/icones/critDamage.png'),
  'diamant': require('../../../assets/grimoire/icones/diamant.png'),
  'dragonnet': require('../../../assets/grimoire/icones/dragonnet.png'),
  'esprit': require('../../../assets/grimoire/icones/esprit.png'),
  'etoilefilante': require('../../../assets/grimoire/icones/etoilefilante.png'),
  'faveur': require('../../../assets/grimoire/icones/faveur.png'),
  'gardien': require('../../../assets/grimoire/icones/gardien.png'),
  'golem': require('../../../assets/grimoire/icones/golem.png'),
  'griffes': require('../../../assets/grimoire/icones/griffes.png'),
  'leviathan': require('../../../assets/grimoire/icones/leviathan.png'),
  'main': require('../../../assets/grimoire/icones/main.png'),
  'offrande': require('../../../assets/grimoire/icones/offrande.png'),
  'oracle': require('../../../assets/grimoire/icones/oracle.png'),
  'pacte': require('../../../assets/grimoire/icones/pacte.png'),
  'phenix': require('../../../assets/grimoire/icones/phenix.png'),
  'piece': require('../../../assets/grimoire/icones/piece.png'),
  'relique:abysseAbyssorax': require('../../../assets/grimoire/icones/relique-abysseAbyssorax.png'),
  'relique:bouclierAegisolar': require('../../../assets/grimoire/icones/relique-bouclierAegisolar.png'),
  'relique:crocBouldog': require('../../../assets/grimoire/icones/relique-crocBouldog.png'),
  'relique:ecailleCaraploof': require('../../../assets/grimoire/icones/relique-ecailleCaraploof.png'),
  'relique:eclatLuxorbe': require('../../../assets/grimoire/icones/relique-eclatLuxorbe.png'),
  'relique:etincelleVoltix': require('../../../assets/grimoire/icones/relique-etincelleVoltix.png'),
  'relique:flammeFournax': require('../../../assets/grimoire/icones/relique-flammeFournax.png'),
  'relique:glypheRunicor': require('../../../assets/grimoire/icones/relique-glypheRunicor.png'),
  'relique:griffeBraisillon': require('../../../assets/grimoire/icones/relique-griffeBraisillon.png'),
  'relique:noyauBrontobloc': require('../../../assets/grimoire/icones/relique-noyauBrontobloc.png'),
  'relique:ombreOmbrillon': require('../../../assets/grimoire/icones/relique-ombreOmbrillon.png'),
  'relique:perleAquamira': require('../../../assets/grimoire/icones/relique-perleAquamira.png'),
  'relique:petaleBraiserose': require('../../../assets/grimoire/icones/relique-petaleBraiserose.png'),
  'relique:pierreTerracroc': require('../../../assets/grimoire/icones/relique-pierreTerracroc.png'),
  'relique:plumeVentis': require('../../../assets/grimoire/icones/relique-plumeVentis.png'),
  'relique:racineRacinea': require('../../../assets/grimoire/icones/relique-racineRacinea.png'),
  'relique:runeGlyphon': require('../../../assets/grimoire/icones/relique-runeGlyphon.png'),
  'relique:sceauMalefix': require('../../../assets/grimoire/icones/relique-sceauMalefix.png'),
  'relique:ventZephyrion': require('../../../assets/grimoire/icones/relique-ventZephyrion.png'),
  'relique:voileNocturis': require('../../../assets/grimoire/icones/relique-voileNocturis.png'),
  'sanctuaire': require('../../../assets/grimoire/icones/sanctuaire.png'),
  'seigneurombres': require('../../../assets/grimoire/icones/seigneurombres.png'),
  'tap1': require('../../../assets/grimoire/icones/tap1.png'),
  'tap10': require('../../../assets/grimoire/icones/tap10.png'),
  'tap2': require('../../../assets/grimoire/icones/tap2.png'),
  'tap3': require('../../../assets/grimoire/icones/tap3.png'),
  'tap4': require('../../../assets/grimoire/icones/tap4.png'),
  'tap5': require('../../../assets/grimoire/icones/tap5.png'),
  'tap6': require('../../../assets/grimoire/icones/tap6.png'),
  'tap7': require('../../../assets/grimoire/icones/tap7.png'),
  'tap8': require('../../../assets/grimoire/icones/tap8.png'),
  'tap9': require('../../../assets/grimoire/icones/tap9.png'),
  'titan': require('../../../assets/grimoire/icones/titan.png'),
  'titanfoudre': require('../../../assets/grimoire/icones/titanfoudre.png'),
  'veilleur': require('../../../assets/grimoire/icones/veilleur.png'),
};
