// ════════════════════════════════════════════════════════════════════
//  LES 252 DÉFIS, ÉCRITS UN PAR UN
// ════════════════════════════════════════════════════════════════════
//
// ⚠️⚠️ CE FICHIER EST LA SOURCE DE VÉRITÉ. Ce qui est écrit ici est
// exactement ce que le joueur reçoit — aucune cible n'est recalculée,
// aucun article n'est résolu, aucun ordre n'est réarrangé.
//
// POURQUOI. Les défis étaient produits à partir de 42 modèles, dont la
// cible, l'article et l'ordre se calculaient au moment du tirage.
// Presque tous les bugs de la semaine venaient de cette résolution,
// jamais des défis eux-mêmes :
//   - « Titan de Foudre » : article résolu par groupe ;
//   - « 3 puis 6 puis 3 » : cible calculée par groupe ;
//   - deux achats collés : ordre recalculé au tirage ;
//   - « 750 pièces » à l'Ascension 5 : tirage initial fait au groupe 0.
//
// Aucun n'aurait existé ici. Une erreur ne peut plus toucher qu'UN défi
// au lieu de se propager aux 210 autres.
//
// ⚠️ LE LIBELLÉ PREND LA CIBLE EN ARGUMENT, il ne l'écrit pas en dur :
// le calculateur d'achats peut RÉDUIRE la demande d'un joueur en avance,
// et le texte doit suivre. Un libellé figé afficherait « Achète 3 » là
// où le jeu n'en réclame qu'un.
//
// ⚠️ Fichier GÉNÉRÉ depuis l'ancien moteur, puis vérifié défi par défi :
// les 252 sorties étaient identiques.
//
// 7 œufs de 6 défis par Ascension, 6 Ascensions écrites. Au-delà, le jeu
// rejoue la dernière.
export const DEFIS_ECRITS = [
  // ── Ascension 0 · œuf 1 ──
  [
    { id: 'a0e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 750, mode: 'delta',
      label: (t) => `Obtiens ${t} pièces` },
    { id: 'a0e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 4, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a0e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 25, mode: 'absolute',
      label: (t) => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a0e1_esprit', icon: '👻', metric: 'auto:esprit',
      target: 3, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
    { id: 'a0e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 3, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a0e1_combo', icon: '🔥', metric: 'maxCombo',
      target: 20, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 0 · œuf 2 ──
  [
    { id: 'a0e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 8, mode: 'absolute',
      label: (t) => `Monte la Faveur des Esprits au niveau ${t}` },
    { id: 'a0e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 7, mode: 'absolute',
      label: (t) => `Atteins ${t} pièces par seconde` },
    { id: 'a0e2_gen0b', icon: '👻', metric: 'auto:esprit',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
    { id: 'a0e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 5, mode: 'absolute',
      label: (t) => `Termine le chapitre 1, niveau ${t}` },
    { id: 'a0e2_crits', icon: '💥', metric: 'totalCrits',
      target: 200, mode: 'delta',
      label: (t) => `Obtiens ${t} coups critiques` },
    { id: 'a0e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 0 · œuf 3 ──
  [
    { id: 'a0e3_reserve', icon: '💰', metric: 'coins',
      target: 25000, mode: 'absolute',
      label: () => 'Mets 25 000 pièces de côté' },
    { id: 'a0e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 10, mode: 'absolute',
      label: (t) => `Monte les Dégâts critiques au niveau ${t}` },
    { id: 'a0e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 10, mode: 'absolute',
      label: (t) => `Termine le chapitre 1, niveau ${t}` },
    { id: 'a0e3_gen1', icon: '⚙️', metric: 'auto:esprit',
      target: 3, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
    { id: 'a0e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 5, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a0e3_tap1b', icon: '🪄', metric: 'critDamageLevel',
      target: 4, mode: 'delta',
      label: (t) => `Monte les Dégâts critiques de ${t} niveaux` },
  ],
  // ── Ascension 0 · œuf 4 ──
  [
    { id: 'a0e4_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta',
      label: () => 'Achète une rune' },
    { id: 'a0e4_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute',
      label: (t) => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a0e4_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', step: 5,
      label: (t) => `Monte une créature au niveau ${t}` },
    { id: 'a0e4_tap0', icon: '✊', metric: 'critLevel',
      target: 4, mode: 'delta',
      label: (t) => `Monte la Faveur des Esprits de ${t} niveaux` },
    { id: 'a0e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta',
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a0e4_tap0b', icon: '✊', metric: 'critDamageLevel',
      target: 7, mode: 'delta',
      label: (t) => `Monte les Dégâts critiques de ${t} niveaux` },
  ],
  // ── Ascension 0 · œuf 5 ──
  [
    { id: 'a0e5_reserve', icon: '💰', metric: 'coins',
      target: 90000, mode: 'absolute',
      label: () => 'Mets 90 000 pièces de côté' },
    { id: 'a0e5_gen2', icon: '⚙️', metric: 'auto:main',
      target: 2, mode: 'delta',
      label: (t) => `Achète ${t} Mains Spectrales` },
    { id: 'a0e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 15, mode: 'absolute',
      label: () => 'Termine le chapitre 2, niveau 5' },
    { id: 'a0e5_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute',
      label: (t) => `Monte le Veilleur au niveau ${t}` },
    { id: 'a0e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a0e5_gen1b', icon: '⚙️', metric: 'auto:esprit',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
  ],
  // ── Ascension 0 · œuf 6 ──
  [
    { id: 'a0e6_coins', icon: '🪙', metric: 'totalEarned',
      target: 120000, mode: 'delta',
      label: () => 'Obtiens 120 000 pièces' },
    { id: 'a0e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 10, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a0e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
    { id: 'a0e6_gen2b', icon: '⚙️', metric: 'auto:main',
      target: 3, mode: 'delta',
      label: (t) => `Achète ${t} Mains Spectrales` },
    { id: 'a0e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 9, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a0e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta',
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 0 · œuf 7 ──
  [
    { id: 'a0e7_reserve', icon: '💰', metric: 'coins',
      target: 150000, mode: 'absolute',
      label: () => 'Mets 150 000 pièces de côté' },
    { id: 'a0e7_tap1', icon: '🪄', metric: 'critLevel',
      target: 7, mode: 'delta',
      label: (t) => `Monte la Faveur des Esprits de ${t} niveaux` },
    { id: 'a0e7_taps', icon: '👆', metric: 'totalTaps',
      target: 1500, mode: 'absolute', minStep: 300,
      label: () => 'Atteins 1 500 taps au total' },
    { id: 'a0e7_combo', icon: '🔥', metric: 'maxCombo',
      target: 30, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
    { id: 'a0e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 9, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a0e7_ascend', icon: '🌟', metric: 'ascension',
      target: 1, mode: 'absolute', step: 1,
      label: () => 'Fais ta 1re Ascension' },
  ],
  // ── Ascension 1 · œuf 1 ──
  [
    { id: 'a1e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 9000, mode: 'delta',
      label: () => 'Obtiens 9 000 pièces' },
    { id: 'a1e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 6, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a1e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a1e1_esprit', icon: '👻', metric: 'auto:esprit',
      target: 4, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
    { id: 'a1e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 5, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a1e1_combo', icon: '🔥', metric: 'maxCombo',
      target: 35, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 1 · œuf 2 ──
  [
    { id: 'a1e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 12, mode: 'absolute',
      label: (t) => `Monte la Faveur des Esprits au niveau ${t}` },
    { id: 'a1e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 85, mode: 'absolute',
      label: (t) => `Atteins ${t} pièces par seconde` },
    { id: 'a1e2_gen0b', icon: '👻', metric: 'auto:esprit',
      target: 7, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
    { id: 'a1e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 20, mode: 'absolute',
      label: () => 'Termine le chapitre 2, niveau 10' },
    { id: 'a1e2_crits', icon: '💥', metric: 'totalCrits',
      target: 340, mode: 'delta',
      label: (t) => `Obtiens ${t} coups critiques` },
    { id: 'a1e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 1 · œuf 3 ──
  [
    { id: 'a1e3_reserve', icon: '💰', metric: 'coins',
      target: 300000, mode: 'absolute',
      label: () => 'Mets 300 000 pièces de côté' },
    { id: 'a1e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 15, mode: 'absolute',
      label: (t) => `Monte les Dégâts critiques au niveau ${t}` },
    { id: 'a1e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 25, mode: 'absolute',
      label: () => 'Termine le chapitre 3, niveau 5' },
    { id: 'a1e3_gen1', icon: '⚙️', metric: 'auto:esprit',
      target: 4, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
    { id: 'a1e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 9, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a1e3_tap1b', icon: '🪄', metric: 'tapUpgrade:tap2',
      target: 6, mode: 'delta',
      label: (t) => `Monte Gantelet d’Obsidienne de ${t} niveaux` },
  ],
  // ── Ascension 1 · œuf 4 ──
  [
    { id: 'a1e4_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta',
      label: () => 'Achète une rune' },
    { id: 'a1e4_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute',
      label: (t) => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a1e4_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', step: 5,
      label: (t) => `Monte une créature au niveau ${t}` },
    { id: 'a1e4_tap0', icon: '✊', metric: 'tapUpgrade:tap1',
      target: 6, mode: 'delta',
      label: (t) => `Monte Poigne Ancienne de ${t} niveaux` },
    { id: 'a1e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta',
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a1e4_tap0b', icon: '✊', metric: 'tapUpgrade:tap2',
      target: 10, mode: 'delta',
      label: (t) => `Monte Gantelet d’Obsidienne de ${t} niveaux` },
  ],
  // ── Ascension 1 · œuf 5 ──
  [
    { id: 'a1e5_reserve', icon: '💰', metric: 'coins',
      target: 1100000, mode: 'absolute',
      label: () => 'Mets 1,1 million de pièces de côté' },
    { id: 'a1e5_gen2', icon: '⚙️', metric: 'auto:main',
      target: 3, mode: 'delta',
      label: (t) => `Achète ${t} Mains Spectrales` },
    { id: 'a1e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 30, mode: 'absolute',
      label: () => 'Termine le chapitre 3, niveau 10' },
    { id: 'a1e5_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute',
      label: (t) => `Monte le Veilleur au niveau ${t}` },
    { id: 'a1e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a1e5_gen1b', icon: '⚙️', metric: 'auto:esprit',
      target: 7, mode: 'delta',
      label: (t) => `Achète ${t} Esprits Frappeurs` },
  ],
  // ── Ascension 1 · œuf 6 ──
  [
    { id: 'a1e6_coins', icon: '🪙', metric: 'totalEarned',
      target: 200000000, mode: 'delta',
      label: () => 'Obtiens 200 millions de pièces' },
    { id: 'a1e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 15, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a1e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
    { id: 'a1e6_gen2b', icon: '⚙️', metric: 'auto:main',
      target: 4, mode: 'delta',
      label: (t) => `Achète ${t} Mains Spectrales` },
    { id: 'a1e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 15, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a1e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta',
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 1 · œuf 7 ──
  [
    { id: 'a1e7_reserve', icon: '💰', metric: 'coins',
      target: 1800000, mode: 'absolute',
      label: () => 'Mets 1,8 million de pièces de côté' },
    { id: 'a1e7_tap1', icon: '🪄', metric: 'tapUpgrade:tap1',
      target: 10, mode: 'delta',
      label: (t) => `Monte Poigne Ancienne de ${t} niveaux` },
    { id: 'a1e7_taps', icon: '👆', metric: 'totalTaps',
      target: 2600, mode: 'absolute', minStep: 300,
      label: () => 'Atteins 2 600 taps au total' },
    { id: 'a1e7_combo', icon: '🔥', metric: 'maxCombo',
      target: 50, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
    { id: 'a1e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 15, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a1e7_ascend', icon: '🌟', metric: 'ascension',
      target: 2, mode: 'absolute', step: 1,
      label: (t) => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 2 · œuf 1 ──
  [
    { id: 'a2e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 68000, mode: 'delta',
      label: () => 'Obtiens 68 000 pièces' },
    { id: 'a2e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 8, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a2e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 70, mode: 'absolute',
      label: (t) => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a2e1_esprit', icon: '👻', metric: 'auto:main',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Mains Spectrales` },
    { id: 'a2e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 8, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a2e1_combo', icon: '🔥', metric: 'maxCombo',
      target: 40, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 2 · œuf 2 ──
  [
    { id: 'a2e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 15, mode: 'absolute',
      label: (t) => `Monte la Faveur des Esprits au niveau ${t}` },
    { id: 'a2e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 630, mode: 'absolute',
      label: (t) => `Atteins ${t} pièces par seconde` },
    { id: 'a2e2_gen0b', icon: '👻', metric: 'auto:main',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Mains Spectrales` },
    { id: 'a2e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 35, mode: 'absolute',
      label: () => 'Termine le chapitre 4, niveau 5' },
    { id: 'a2e2_crits', icon: '💥', metric: 'totalCrits',
      target: 500, mode: 'delta',
      label: (t) => `Obtiens ${t} coups critiques` },
    { id: 'a2e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 2 · œuf 3 ──
  [
    { id: 'a2e3_reserve', icon: '💰', metric: 'coins',
      target: 2300000, mode: 'absolute',
      label: () => 'Mets 2,3 millions de pièces de côté' },
    { id: 'a2e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 19, mode: 'absolute',
      label: (t) => `Monte les Dégâts critiques au niveau ${t}` },
    { id: 'a2e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 40, mode: 'absolute',
      label: () => 'Termine le chapitre 4, niveau 10' },
    { id: 'a2e3_gen1', icon: '⚙️', metric: 'auto:automate',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Automates Runiques` },
    { id: 'a2e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 13, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a2e3_tap1b', icon: '🪄', metric: 'tapUpgrade:tap4',
      target: 8, mode: 'delta',
      label: (t) => `Monte Poing de Granit de ${t} niveaux` },
  ],
  // ── Ascension 2 · œuf 4 ──
  [
    { id: 'a2e4_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta',
      label: () => 'Achète une rune' },
    { id: 'a2e4_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute',
      label: (t) => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a2e4_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', step: 5,
      label: (t) => `Monte une créature au niveau ${t}` },
    { id: 'a2e4_tap0', icon: '✊', metric: 'tapUpgrade:tap3',
      target: 8, mode: 'delta',
      label: (t) => `Monte Sceau de Puissance de ${t} niveaux` },
    { id: 'a2e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta',
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a2e4_tap0b', icon: '✊', metric: 'tapUpgrade:tap4',
      target: 11, mode: 'delta',
      label: (t) => `Monte Poing de Granit de ${t} niveaux` },
  ],
  // ── Ascension 2 · œuf 5 ──
  [
    { id: 'a2e5_reserve', icon: '💰', metric: 'coins',
      target: 8100000, mode: 'absolute',
      label: () => 'Mets 8,1 millions de pièces de côté' },
    { id: 'a2e5_gen2', icon: '⚙️', metric: 'auto:colonie',
      target: 3, mode: 'delta',
      label: (t) => `Achète ${t} Colonies de Familiers` },
    { id: 'a2e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 45, mode: 'absolute',
      label: () => 'Termine le chapitre 5, niveau 5' },
    { id: 'a2e5_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute',
      label: (t) => `Monte le Veilleur au niveau ${t}` },
    { id: 'a2e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a2e5_gen1b', icon: '⚙️', metric: 'auto:automate',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Automates Runiques` },
  ],
  // ── Ascension 2 · œuf 6 ──
  [
    { id: 'a2e6_coins', icon: '🪙', metric: 'totalEarned',
      target: 680000000, mode: 'delta',
      label: () => 'Obtiens 680 millions de pièces' },
    { id: 'a2e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 19, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a2e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
    { id: 'a2e6_gen2b', icon: '⚙️', metric: 'auto:colonie',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Colonies de Familiers` },
    { id: 'a2e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 23, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a2e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta',
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 2 · œuf 7 ──
  [
    { id: 'a2e7_reserve', icon: '💰', metric: 'coins',
      target: 14000000, mode: 'absolute',
      label: () => 'Mets 14 millions de pièces de côté' },
    { id: 'a2e7_tap1', icon: '🪄', metric: 'tapUpgrade:tap3',
      target: 11, mode: 'delta',
      label: (t) => `Monte Sceau de Puissance de ${t} niveaux` },
    { id: 'a2e7_taps', icon: '👆', metric: 'totalTaps',
      target: 3800, mode: 'absolute', minStep: 300,
      label: () => 'Atteins 3 800 taps au total' },
    { id: 'a2e7_combo', icon: '🔥', metric: 'maxCombo',
      target: 50, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
    { id: 'a2e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 23, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a2e7_ascend', icon: '🌟', metric: 'ascension',
      target: 3, mode: 'absolute', step: 1,
      label: (t) => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 3 · œuf 1 ──
  [
    { id: 'a3e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 530000, mode: 'delta',
      label: () => 'Obtiens 530 000 pièces' },
    { id: 'a3e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 10, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a3e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 90, mode: 'absolute',
      label: (t) => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a3e1_esprit', icon: '👻', metric: 'auto:colonie',
      target: 6, mode: 'delta',
      label: (t) => `Achète ${t} Colonies de Familiers` },
    { id: 'a3e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 10, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a3e1_combo', icon: '🔥', metric: 'maxCombo',
      target: 40, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 3 · œuf 2 ──
  [
    { id: 'a3e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 19, mode: 'absolute',
      label: (t) => `Monte la Faveur des Esprits au niveau ${t}` },
    { id: 'a3e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 4900, mode: 'absolute',
      label: () => 'Atteins 4 900 pièces par seconde' },
    { id: 'a3e2_gen0b', icon: '👻', metric: 'auto:colonie',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Colonies de Familiers` },
    { id: 'a3e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 50, mode: 'absolute',
      label: () => 'Termine le chapitre 5, niveau 10' },
    { id: 'a3e2_crits', icon: '💥', metric: 'totalCrits',
      target: 660, mode: 'delta',
      label: (t) => `Obtiens ${t} coups critiques` },
    { id: 'a3e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 3 · œuf 3 ──
  [
    { id: 'a3e3_reserve', icon: '💰', metric: 'coins',
      target: 18000000, mode: 'absolute',
      label: () => 'Mets 18 millions de pièces de côté' },
    { id: 'a3e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 24, mode: 'absolute',
      label: (t) => `Monte les Dégâts critiques au niveau ${t}` },
    { id: 'a3e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 55, mode: 'absolute',
      label: () => 'Termine le chapitre 6, niveau 5' },
    { id: 'a3e3_gen1', icon: '⚙️', metric: 'auto:titan',
      target: 6, mode: 'delta',
      label: (t) => `Achète ${t} Titans Mécaniques` },
    { id: 'a3e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 17, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a3e3_tap1b', icon: '🪄', metric: 'tapUpgrade:tap6',
      target: 10, mode: 'delta',
      label: (t) => `Monte Coeur de Supernova de ${t} niveaux` },
  ],
  // ── Ascension 3 · œuf 4 ──
  [
    { id: 'a3e4_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta',
      label: () => 'Achète une rune' },
    { id: 'a3e4_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute',
      label: (t) => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a3e4_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', step: 5,
      label: (t) => `Monte une créature au niveau ${t}` },
    { id: 'a3e4_tap0', icon: '✊', metric: 'tapUpgrade:tap5',
      target: 10, mode: 'delta',
      label: (t) => `Monte Éclat Primordial de ${t} niveaux` },
    { id: 'a3e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta',
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a3e4_tap0b', icon: '✊', metric: 'tapUpgrade:tap6',
      target: 11, mode: 'delta',
      label: (t) => `Monte Coeur de Supernova de ${t} niveaux` },
  ],
  // ── Ascension 3 · œuf 5 ──
  [
    { id: 'a3e5_reserve', icon: '💰', metric: 'coins',
      target: 63000000, mode: 'absolute',
      label: () => 'Mets 63 millions de pièces de côté' },
    { id: 'a3e5_gen2', icon: '⚙️', metric: 'auto:golem',
      target: 4, mode: 'delta',
      label: (t) => `Achète ${t} Golems de Cristal` },
    { id: 'a3e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 60, mode: 'absolute',
      label: () => 'Termine le chapitre 6, niveau 10' },
    { id: 'a3e5_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute',
      label: (t) => `Monte le Veilleur au niveau ${t}` },
    { id: 'a3e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a3e5_gen1b', icon: '⚙️', metric: 'auto:titan',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Titans Mécaniques` },
  ],
  // ── Ascension 3 · œuf 6 ──
  [
    { id: 'a3e6_coins', icon: '🪙', metric: 'totalEarned',
      target: 2900000000, mode: 'delta',
      label: () => 'Obtiens 2,9 milliards de pièces' },
    { id: 'a3e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 23, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a3e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
    { id: 'a3e6_gen2b', icon: '⚙️', metric: 'auto:golem',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Golems de Cristal` },
    { id: 'a3e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 30, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a3e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta',
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 3 · œuf 7 ──
  [
    { id: 'a3e7_reserve', icon: '💰', metric: 'coins',
      target: 110000000, mode: 'absolute',
      label: () => 'Mets 110 millions de pièces de côté' },
    { id: 'a3e7_tap1', icon: '🪄', metric: 'tapUpgrade:tap5',
      target: 11, mode: 'delta',
      label: (t) => `Monte Éclat Primordial de ${t} niveaux` },
    { id: 'a3e7_taps', icon: '👆', metric: 'totalTaps',
      target: 5000, mode: 'absolute', minStep: 300,
      label: () => 'Atteins 5 000 taps au total' },
    { id: 'a3e7_combo', icon: '🔥', metric: 'maxCombo',
      target: 50, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
    { id: 'a3e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 30, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a3e7_ascend', icon: '🌟', metric: 'ascension',
      target: 4, mode: 'absolute', step: 1,
      label: (t) => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 4 · œuf 1 ──
  [
    { id: 'a4e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 3200000, mode: 'delta',
      label: () => 'Obtiens 3,2 millions de pièces' },
    { id: 'a4e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 11, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a4e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 110, mode: 'absolute',
      label: (t) => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a4e1_esprit', icon: '👻', metric: 'auto:golem',
      target: 7, mode: 'delta',
      label: (t) => `Achète ${t} Golems de Cristal` },
    { id: 'a4e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 12, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a4e1_combo', icon: '🔥', metric: 'maxCombo',
      target: 40, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 4 · œuf 2 ──
  [
    { id: 'a4e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 20, mode: 'absolute',
      label: (t) => `Monte la Faveur des Esprits au niveau ${t}` },
    { id: 'a4e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 29000, mode: 'absolute',
      label: () => 'Atteins 29 000 pièces par seconde' },
    { id: 'a4e2_gen0b', icon: '👻', metric: 'auto:golem',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Golems de Cristal` },
    { id: 'a4e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 65, mode: 'absolute',
      label: () => 'Termine le chapitre 7, niveau 5' },
    { id: 'a4e2_crits', icon: '💥', metric: 'totalCrits',
      target: 800, mode: 'delta',
      label: (t) => `Obtiens ${t} coups critiques` },
    { id: 'a4e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 4 · œuf 3 ──
  [
    { id: 'a4e3_reserve', icon: '💰', metric: 'coins',
      target: 110000000, mode: 'absolute',
      label: () => 'Mets 110 millions de pièces de côté' },
    { id: 'a4e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 24, mode: 'absolute',
      label: (t) => `Monte les Dégâts critiques au niveau ${t}` },
    { id: 'a4e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 70, mode: 'absolute',
      label: () => 'Termine le chapitre 7, niveau 10' },
    { id: 'a4e3_gen1', icon: '⚙️', metric: 'auto:dragonnet',
      target: 7, mode: 'delta',
      label: (t) => `Achète ${t} Dragons Miniatures` },
    { id: 'a4e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 20, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a4e3_tap1b', icon: '🪄', metric: 'tapUpgrade:tap8',
      target: 11, mode: 'delta',
      label: (t) => `Monte Serment Éternel de ${t} niveaux` },
  ],
  // ── Ascension 4 · œuf 4 ──
  [
    { id: 'a4e4_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta',
      label: () => 'Achète une rune' },
    { id: 'a4e4_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute',
      label: (t) => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a4e4_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', step: 5,
      label: (t) => `Monte une créature au niveau ${t}` },
    { id: 'a4e4_tap0', icon: '✊', metric: 'tapUpgrade:tap7',
      target: 11, mode: 'delta',
      label: (t) => `Monte Griffe du Vide de ${t} niveaux` },
    { id: 'a4e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta',
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a4e4_tap0b', icon: '✊', metric: 'tapUpgrade:tap8',
      target: 11, mode: 'delta',
      label: (t) => `Monte Serment Éternel de ${t} niveaux` },
  ],
  // ── Ascension 4 · œuf 5 ──
  [
    { id: 'a4e5_reserve', icon: '💰', metric: 'coins',
      target: 380000000, mode: 'absolute',
      label: () => 'Mets 380 millions de pièces de côté' },
    { id: 'a4e5_gen2', icon: '⚙️', metric: 'auto:phenix',
      target: 4, mode: 'delta',
      label: (t) => `Achète ${t} Phénix Renaissants` },
    { id: 'a4e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 75, mode: 'absolute',
      label: () => 'Termine le chapitre 8, niveau 5' },
    { id: 'a4e5_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute',
      label: (t) => `Monte le Veilleur au niveau ${t}` },
    { id: 'a4e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a4e5_gen1b', icon: '⚙️', metric: 'auto:dragonnet',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Dragons Miniatures` },
  ],
  // ── Ascension 4 · œuf 6 ──
  [
    { id: 'a4e6_coins', icon: '🪙', metric: 'totalEarned',
      target: 13000000000, mode: 'delta',
      label: () => 'Obtiens 13 milliards de pièces' },
    { id: 'a4e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 23, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a4e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
    { id: 'a4e6_gen2b', icon: '⚙️', metric: 'auto:phenix',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Phénix Renaissants` },
    { id: 'a4e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 35, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a4e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta',
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 4 · œuf 7 ──
  [
    { id: 'a4e7_reserve', icon: '💰', metric: 'coins',
      target: 630000000, mode: 'absolute',
      label: () => 'Mets 630 millions de pièces de côté' },
    { id: 'a4e7_tap1', icon: '🪄', metric: 'tapUpgrade:tap7',
      target: 11, mode: 'delta',
      label: (t) => `Monte Griffe du Vide de ${t} niveaux` },
    { id: 'a4e7_taps', icon: '👆', metric: 'totalTaps',
      target: 6000, mode: 'absolute', minStep: 300,
      label: () => 'Atteins 6 000 taps au total' },
    { id: 'a4e7_combo', icon: '🔥', metric: 'maxCombo',
      target: 50, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
    { id: 'a4e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 35, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a4e7_ascend', icon: '🌟', metric: 'ascension',
      target: 5, mode: 'absolute', step: 1,
      label: (t) => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 5 · œuf 1 ──
  [
    { id: 'a5e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 10000000, mode: 'delta',
      label: () => 'Obtiens 10 millions de pièces' },
    { id: 'a5e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 13, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a5e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 130, mode: 'absolute',
      label: (t) => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a5e1_esprit', icon: '👻', metric: 'auto:phenix',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Phénix Renaissants` },
    { id: 'a5e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 14, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a5e1_combo', icon: '🔥', metric: 'maxCombo',
      target: 40, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 5 · œuf 2 ──
  [
    { id: 'a5e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 20, mode: 'absolute',
      label: (t) => `Monte la Faveur des Esprits au niveau ${t}` },
    { id: 'a5e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 93000, mode: 'absolute',
      label: () => 'Atteins 93 000 pièces par seconde' },
    { id: 'a5e2_gen0b', icon: '👻', metric: 'auto:phenix',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Phénix Renaissants` },
    { id: 'a5e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 80, mode: 'absolute',
      label: () => 'Termine le chapitre 8, niveau 10' },
    { id: 'a5e2_crits', icon: '💥', metric: 'totalCrits',
      target: 930, mode: 'delta',
      label: (t) => `Obtiens ${t} coups critiques` },
    { id: 'a5e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 5 · œuf 3 ──
  [
    { id: 'a5e3_reserve', icon: '💰', metric: 'coins',
      target: 330000000, mode: 'absolute',
      label: () => 'Mets 330 millions de pièces de côté' },
    { id: 'a5e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 24, mode: 'absolute',
      label: (t) => `Monte les Dégâts critiques au niveau ${t}` },
    { id: 'a5e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 85, mode: 'absolute',
      label: () => 'Termine le chapitre 9, niveau 5' },
    { id: 'a5e3_gen1', icon: '⚙️', metric: 'auto:leviathan',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Léviathans des Abysses` },
    { id: 'a5e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 23, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a5e3_tap1b', icon: '🪄', metric: 'tapUpgrade:tap10',
      target: 11, mode: 'delta',
      label: (t) => `Monte Volonté du Paradoxe de ${t} niveaux` },
  ],
  // ── Ascension 5 · œuf 4 ──
  [
    { id: 'a5e4_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta',
      label: () => 'Achète une rune' },
    { id: 'a5e4_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute',
      label: (t) => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a5e4_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', step: 5,
      label: (t) => `Monte une créature au niveau ${t}` },
    { id: 'a5e4_tap0', icon: '✊', metric: 'tapUpgrade:tap9',
      target: 11, mode: 'delta',
      label: (t) => `Monte Fracture du Réel de ${t} niveaux` },
    { id: 'a5e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta',
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a5e4_tap0b', icon: '✊', metric: 'tapUpgrade:tap10',
      target: 11, mode: 'delta',
      label: (t) => `Monte Volonté du Paradoxe de ${t} niveaux` },
  ],
  // ── Ascension 5 · œuf 5 ──
  [
    { id: 'a5e5_reserve', icon: '💰', metric: 'coins',
      target: 1200000000, mode: 'absolute',
      label: () => 'Mets 1,2 milliard de pièces de côté' },
    { id: 'a5e5_gen2', icon: '⚙️', metric: 'auto:gardien',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Gardiens Célestes` },
    { id: 'a5e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 90, mode: 'absolute',
      label: () => 'Termine le chapitre 9, niveau 10' },
    { id: 'a5e5_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute',
      label: (t) => `Monte le Veilleur au niveau ${t}` },
    { id: 'a5e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 45, mode: 'absolute',
      label: (t) => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a5e5_gen1b', icon: '⚙️', metric: 'auto:leviathan',
      target: 8, mode: 'delta',
      label: (t) => `Achète ${t} Léviathans des Abysses` },
  ],
  // ── Ascension 5 · œuf 6 ──
  [
    { id: 'a5e6_coins', icon: '🪙', metric: 'totalEarned',
      target: 76000000000, mode: 'delta',
      label: () => 'Obtiens 76 milliards de pièces' },
    { id: 'a5e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 23, mode: 'absolute',
      label: (t) => `Monte Pacte au niveau ${t}` },
    { id: 'a5e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta',
      label: (t) => `Gagne ${t} combats en Aventure` },
    { id: 'a5e6_gen2b', icon: '⚙️', metric: 'auto:gardien',
      target: 5, mode: 'delta',
      label: (t) => `Achète ${t} Gardiens Célestes` },
    { id: 'a5e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 40, mode: 'delta',
      label: (t) => `Touche ${t} fois la cible dorée` },
    { id: 'a5e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta',
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 5 · œuf 7 ──
  [
    { id: 'a5e7_reserve', icon: '💰', metric: 'coins',
      target: 2000000000, mode: 'absolute',
      label: () => 'Mets 2 milliards de pièces de côté' },
    { id: 'a5e7_tap1', icon: '🪄', metric: 'tapUpgrade:tap9',
      target: 11, mode: 'delta',
      label: (t) => `Monte Fracture du Réel de ${t} niveaux` },
    { id: 'a5e7_taps', icon: '👆', metric: 'totalTaps',
      target: 7000, mode: 'absolute', minStep: 300,
      label: () => 'Atteins 7 000 taps au total' },
    { id: 'a5e7_combo', icon: '🔥', metric: 'maxCombo',
      target: 50, mode: 'absolute',
      label: (t) => `Enchaîne ${t} taps sans pause` },
    { id: 'a5e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 40, mode: 'delta',
      label: (t) => `Active ${t} fois un pouvoir` },
    { id: 'a5e7_ascend', icon: '🌟', metric: 'ascension',
      target: 6, mode: 'absolute', step: 1,
      label: (t) => `Fais ta ${t}e Ascension` },
  ],
];
