// ════════════════════════════════════════════════════════════════════
//  LES 252 DÉFIS, ÉCRITS UN PAR UN
// ════════════════════════════════════════════════════════════════════
//
// ⚠️⚠️ CE FICHIER EST LA SOURCE DE VÉRITÉ. Ce qui est écrit ici est
// exactement ce que le joueur reçoit — aucune cible n'est recalculée,
// aucun article n'est résolu, aucun ordre n'est réarrangé.
//
// POURQUOI. Les défis étaient produits à partir de 42 modèles, dont la
// cible, l'article et l'ordre se calculaient au moment du tirage.
// Presque tous les bugs de la semaine venaient de cette résolution,
// jamais des défis eux-mêmes :
//   - « Titan de Foudre » : article résolu par groupe ;
//   - « 3 puis 6 puis 3 » : cible calculée par groupe ;
//   - deux achats collés : ordre recalculé au tirage ;
//   - « 750 pièces » à l'Ascension 5 : tirage initial fait au groupe 0.
//
// Aucun n'aurait existé ici. Une erreur ne peut plus toucher qu'UN défi
// au lieu de se propager aux 210 autres.
//
// ⚠️ LE LIBELLÉ PREND LA CIBLE EN ARGUMENT, il ne l'écrit pas en dur :
// le calculateur d'achats peut RÉDUIRE la demande d'un joueur en avance,
// et le texte doit suivre. Un libellé figé afficherait « Achète 3 » là
// où le jeu n'en réclame qu'un.
//
// ⚠️ Fichier GÉNÉRÉ depuis l'ancien moteur, puis vérifié défi par défi :
// les 252 sorties étaient identiques.
//
// ⚠️ `fige: true` sur chaque défi : la cible est FINALE et ne doit
// jamais être remise à l'échelle. Sans ce marqueur, le moteur
// appliquait encore son multiplicateur de groupe par-dessus des valeurs
// déjà mises à l'échelle.
//
// 7 œufs de 6 défis par Ascension, 6 Ascensions écrites. Au-delà, le jeu
// rejoue la dernière.
// ⚠️ `fmtQ` écrit un nombre lisible (« 29 000 », « 1,2 million »). Le
// fichier n'importait rien jusqu'ici : tous ses libellés avaient leur
// nombre en dur. Les défis de passif de l'œuf 6, ajoutés le 21/09, sont
// les premiers à le formater — sans cet import, le jeu aurait planté à
// l'affichage du défi.
import { fmtQ, qtyQ, describeAdventureLevel } from './questFormat';

export const DEFIS_ECRITS = [
  // ── Ascension 0 · œuf 1 ──
  [
    { id: 'a0e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 750, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} pièces` },
    { id: 'a0e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a0e1_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 30, mode: 'absolute', fige: true,
      label: t => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a0e1_tap', icon: '✊', metric: 'critLevel',
      target: 7, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a0e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 3, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a0e1_tap1b', icon: '🪄', metric: 'critDamageLevel',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a0e1_crits', icon: '💥', metric: 'totalCrits',
      target: 20, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a0e1_cote', icon: '💰', metric: 'coins',
      target: 12000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
  ],
  // ── Ascension 0 · œuf 2 ──
  [
    { id: 'a0e2_gen', icon: '⚙️', metric: 'auto:main',
      target: 2, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Mains Spectrales' : 'Main Spectrale'}` },
    { id: 'a0e2_reserve', icon: '💰', metric: 'coins',
      target: 18000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a0e2_gen2', icon: '⚙️', metric: 'auto:esprit',
      target: 3, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a0e2_plusB', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 32, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a0e2_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute', fige: true,
      label: t => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a0e2_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', fige: true, step: 5,
      label: t => `Monte une créature au niveau ${t}` },
    { id: 'a0e2_tap', icon: '🪄', metric: 'critLevel',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a0e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 5, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
  ],
  // ── Ascension 0 · œuf 3 ──
  [
    { id: 'a0e3_gen2b', icon: '⚙️', metric: 'auto:main',
      target: 3, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Mains Spectrales' : 'Main Spectrale'}` },
    { id: 'a0e3_plusC', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 35, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a0e3_esprit', icon: '👻', metric: 'auto:esprit',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a0e3_plusC2', icon: '⭐', metric: 'goldenClaimed',
      target: 5, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a0e3_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a0e3_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Achète une rune' },
    { id: 'a0e3_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 140, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a0e3_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Monte le Veilleur au niveau ${t}` },
  ],
  // ── Ascension 0 · œuf 4 ──
  [
    { id: 'a0e4_taps', icon: '👆', metric: 'totalTaps',
      target: 1500, mode: 'absolute', fige: true, minStep: 300,
      label: t => `Atteins ${fmtQ(t)} taps au total` },
    { id: 'a0e4_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 14, mode: 'absolute', fige: true,
      label: t => `Atteins ${t} pièces par seconde` },
    { id: 'a0e4_plusC', icon: '🔥', metric: 'maxTapStreak',
      target: 180, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a0e4_gen0b', icon: '👻', metric: 'auto:esprit',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a0e4_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 5, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a0e4_plusB', icon: '💰', metric: 'coins',
      target: 38000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a0e4_plusC2', icon: '⚔️', metric: 'advLevelReached',
      target: 10, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a0e4_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
  ],
  // ── Ascension 0 · œuf 5 ──
  [
    { id: 'a0e5_pacte', icon: '🔗', metric: 'tapPower',
      target: 3, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a0e5_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 360, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a0e5_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 9, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a0e5_plusC', icon: '⚙️', metric: 'passiveIncome',
      target: 16, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a0e5_reserve', icon: '💰', metric: 'coins',
      target: 44000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a0e5_faveur', icon: '🍀', metric: 'critLevel',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a0e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 38, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a0e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 15, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
  ],
  // ── Ascension 0 · œuf 6 ──
  [
    { id: 'a0e6_plusB', icon: '✨', metric: 'powerActivated',
      target: 11, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a0e6_gen1b', icon: '⚙️', metric: 'auto:esprit',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a0e6_plusB2', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a0e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 6, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a0e6_reserve', icon: '💰', metric: 'coins',
      target: 51000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a0e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Fais une Offrande' },
    { id: 'a0e6_tap0b', icon: '✊', metric: 'critDamageLevel',
      target: 11, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a0e6_crits', icon: '💥', metric: 'totalCrits',
      target: 120, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
  ],
  // ── Ascension 0 · œuf 7 ──
  [
    { id: 'a0e7_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 30, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a0e7_plusC', icon: '✨', metric: 'powerActivated',
      target: 12, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a0e7_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a0e7_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 2, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a0e7_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 18, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a0e7_plusB', icon: '⭐', metric: 'goldenClaimed',
      target: 7, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a0e7_plusB2', icon: '💥', metric: 'totalCrits',
      target: 240, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a0e7_ascend', icon: '🌟', metric: 'ascension',
      target: 1, mode: 'absolute', fige: true, step: 1,
      label: t => `Fais ta ${t}${t === 1 ? 're' : 'e'} Ascension` },
  ],
  // ── Ascension 1 · œuf 1 ──
  [
    { id: 'a1e1_esprit', icon: '👻', metric: 'auto:esprit',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a1e1_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 20, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a1e1_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 13, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a1e1_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 8, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a1e1_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute', fige: true,
      label: t => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a1e1_reserve', icon: '💰', metric: 'coins',
      target: 45000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a1e1_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', fige: true, step: 5,
      label: t => `Monte une créature au niveau ${t}` },
    { id: 'a1e1_gen', icon: '⚙️', metric: 'auto:main',
      target: 3, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Mains Spectrales' : 'Main Spectrale'}` },
  ],
  // ── Ascension 1 · œuf 2 ──
  [
    { id: 'a1e2_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Achète une rune' },
    { id: 'a1e2_plusB', icon: '✨', metric: 'powerActivated',
      target: 14, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a1e2_crits', icon: '💥', metric: 'totalCrits',
      target: 340, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a1e2_gen', icon: '⚙️', metric: 'auto:esprit',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a1e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 25, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a1e2_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a1e2_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Monte le Veilleur au niveau ${t}` },
    { id: 'a1e2_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 41, mode: 'absolute', fige: true,
      label: t => `Reste en Transe x2,5 pendant ${t} secondes` },
  ],
  // ── Ascension 1 · œuf 3 ──
  [
    { id: 'a1e3_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 21, mode: 'absolute', fige: true,
      label: t => `Atteins ${t} pièces par seconde` },
    { id: 'a1e3_plusC', icon: '💥', metric: 'totalCrits',
      target: 680, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a1e3_pacte', icon: '🔗', metric: 'tapPower',
      target: 9, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a1e3_coins', icon: '🪙', metric: 'totalEarned',
      target: 9000, mode: 'delta', fige: true,
      label: () => 'Obtiens 9 000 pièces' },
    { id: 'a1e3_plusB', icon: '⚔️', metric: 'advLevelReached',
      target: 30, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a1e3_faveur', icon: '🍀', metric: 'critLevel',
      target: 12, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a1e3_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 195, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a1e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 15, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
  ],
  // ── Ascension 1 · œuf 4 ──
  [
    { id: 'a1e4_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 60, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a1e4_gen2b', icon: '⚙️', metric: 'auto:main',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Mains Spectrales' : 'Main Spectrale'}` },
    { id: 'a1e4_plusC', icon: '⭐', metric: 'goldenClaimed',
      target: 9, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a1e4_plusC2', icon: '⚙️', metric: 'passiveIncome',
      target: 28, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a1e4_tap', icon: '✊', metric: 'tapUpgrade:tap1',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Poigne Ancienne` },
    { id: 'a1e4_plusB', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 44, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a1e4_reserve', icon: '💰', metric: 'coins',
      target: 85000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a1e4_tap1b', icon: '🪄', metric: 'tapUpgrade:tap2',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Gantelet d’Obsidienne` },
  ],
  // ── Ascension 1 · œuf 5 ──
  [
    { id: 'a1e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 48, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a1e5_plusB', icon: '🔥', metric: 'maxTapStreak',
      target: 210, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a1e5_plusC', icon: '⚔️', metric: 'advLevelReached',
      target: 120, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a1e5_gen0b', icon: '👻', metric: 'auto:esprit',
      target: 7, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a1e5_plusC2', icon: '💰', metric: 'coins',
      target: 98000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a1e5_taps', icon: '👆', metric: 'totalTaps',
      target: 2600, mode: 'absolute', fige: true, minStep: 300,
      label: t => `Atteins ${fmtQ(t)} taps au total` },
    { id: 'a1e5_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 15, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a1e5_taps2', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 1 · œuf 6 ──
  [
    { id: 'a1e6_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 32, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a1e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 10, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a1e6_gen1b', icon: '⚙️', metric: 'auto:esprit',
      target: 7, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Esprits Frappeurs' : 'Esprit Frappeur'}` },
    { id: 'a1e6_plusB', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a1e6_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Fais une Offrande' },
    { id: 'a1e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a1e6_plusC', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a1e6_reserve', icon: '💰', metric: 'coins',
      target: 110000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
  ],
  // ── Ascension 1 · œuf 7 ──
  [
    { id: 'a1e7_plusC', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 52, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a1e7_tap', icon: '🪄', metric: 'tapUpgrade:tap1',
      target: 2, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Poigne Ancienne` },
    { id: 'a1e7_plusB', icon: '⭐', metric: 'goldenClaimed',
      target: 12, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a1e7_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a1e7_tap0b', icon: '✊', metric: 'tapUpgrade:tap2',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Gantelet d’Obsidienne` },
    { id: 'a1e7_plusB2', icon: '⚙️', metric: 'passiveIncome',
      target: 37, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a1e7_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a1e7_ascend', icon: '🌟', metric: 'ascension',
      target: 2, mode: 'absolute', fige: true, step: 1,
      label: t => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 2 · œuf 1 ──
  [
    { id: 'a2e1_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute', fige: true,
      label: t => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a2e1_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 35, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a2e1_taps', icon: '👆', metric: 'totalTaps',
      target: 3800, mode: 'absolute', fige: true, minStep: 300,
      label: t => `Atteins ${fmtQ(t)} taps au total` },
    { id: 'a2e1_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 16, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a2e1_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Monte le Veilleur au niveau ${t}` },
    { id: 'a2e1_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Achète une rune' },
    { id: 'a2e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 68000, mode: 'delta', fige: true,
      label: () => 'Obtiens 68 000 pièces' },
    { id: 'a2e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 9, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
  ],
  // ── Ascension 2 · œuf 2 ──
  [
    { id: 'a2e2_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 47, mode: 'absolute', fige: true,
      label: t => `Atteins ${t} pièces par seconde` },
    { id: 'a2e2_crits', icon: '💥', metric: 'totalCrits',
      target: 500, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a2e2_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 13, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a2e2_esprit', icon: '👻', metric: 'auto:main',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Mains Spectrales' : 'Main Spectrale'}` },
    { id: 'a2e2_plusB', icon: '✨', metric: 'powerActivated',
      target: 17, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a2e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a2e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 15, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a2e2_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Fais une Offrande' },
  ],
  // ── Ascension 2 · œuf 3 ──
  [
    { id: 'a2e3_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a2e3_plusC', icon: '⚙️', metric: 'passiveIncome',
      target: 130, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a2e3_gen0b', icon: '👻', metric: 'auto:main',
      target: 13, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Mains Spectrales' : 'Main Spectrale'}` },
    { id: 'a2e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 18, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a2e3_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', fige: true, step: 5,
      label: t => `Monte une créature au niveau ${t}` },
    { id: 'a2e3_tap', icon: '✊', metric: 'tapUpgrade:tap3',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Sceau de Puissance` },
    { id: 'a2e3_plusC2', icon: '💥', metric: 'totalCrits',
      target: 1000, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a2e3_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 56, mode: 'absolute', fige: true,
      label: t => `Reste en Transe x2,5 pendant ${t} secondes` },
  ],
  // ── Ascension 2 · œuf 4 ──
  [
    { id: 'a2e4_reserve', icon: '💰', metric: 'coins',
      target: 880000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a2e4_gen', icon: '⚙️', metric: 'auto:automate',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Automates Runiques' : 'Automate Runique'}` },
    { id: 'a2e4_plusB', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a2e4_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 230, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a2e4_gen2', icon: '⚙️', metric: 'auto:colonie',
      target: 3, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Colonies de Familiers' : 'Colonie de Familiers'}` },
    { id: 'a2e4_plusB2', icon: '⚔️', metric: 'advLevelReached',
      target: 45, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a2e4_plusB3', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 60, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a2e4_tap1b', icon: '🪄', metric: 'tapUpgrade:tap4',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Poing de Granit` },
  ],
  // ── Ascension 2 · œuf 5 ──
  [
    { id: 'a2e5_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 170, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a2e5_plusB', icon: '🔥', metric: 'maxTapStreak',
      target: 250, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a2e5_reserve', icon: '💰', metric: 'coins',
      target: 1300000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a2e5_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 17, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a2e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 90, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a2e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 65, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a2e5_gen2b', icon: '⚙️', metric: 'auto:colonie',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Colonies de Familiers' : 'Colonie de Familiers'}` },
    { id: 'a2e5_plusC', icon: '⭐', metric: 'goldenClaimed',
      target: 15, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
  ],
  // ── Ascension 2 · œuf 6 ──
  [
    { id: 'a2e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 17, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a2e6_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a2e6_pacte', icon: '🔗', metric: 'tapPower',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a2e6_plusC', icon: '⚔️', metric: 'advLevelReached',
      target: 180, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a2e6_plusC2', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a2e6_gen1b', icon: '⚙️', metric: 'auto:automate',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Automates Runiques' : 'Automate Runique'}` },
    { id: 'a2e6_plusC3', icon: '💰', metric: 'coins',
      target: 1500000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a2e6_plusC4', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 71, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
  ],
  // ── Ascension 2 · œuf 7 ──
  [
    { id: 'a2e7_plusB', icon: '⭐', metric: 'goldenClaimed',
      target: 19, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a2e7_tap', icon: '🪄', metric: 'tapUpgrade:tap3',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Sceau de Puissance` },
    { id: 'a2e7_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a2e7_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a2e7_tap0b', icon: '✊', metric: 'tapUpgrade:tap4',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Poing de Granit` },
    { id: 'a2e7_reserve', icon: '💰', metric: 'coins',
      target: 4400000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a2e7_plusB2', icon: '⚙️', metric: 'passiveIncome',
      target: 200, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a2e7_ascend', icon: '🌟', metric: 'ascension',
      target: 3, mode: 'absolute', fige: true, step: 1,
      label: t => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 3 · œuf 1 ──
  [
    { id: 'a3e1_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute', fige: true,
      label: t => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a3e1_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 50, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a3e1_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', fige: true, step: 5,
      label: t => `Monte une créature au niveau ${t}` },
    { id: 'a3e1_coins', icon: '🪙', metric: 'totalEarned',
      target: 530000, mode: 'delta', fige: true,
      label: () => 'Obtiens 530 000 pièces' },
    { id: 'a3e1_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Monte le Veilleur au niveau ${t}` },
    { id: 'a3e1_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 270, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a3e1_taps', icon: '👆', metric: 'totalTaps',
      target: 5000, mode: 'absolute', fige: true, minStep: 300,
      label: t => `Atteins ${fmtQ(t)} taps au total` },
    { id: 'a3e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 9, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
  ],
  // ── Ascension 3 · œuf 2 ──
  [
    { id: 'a3e2_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 19, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a3e2_crits', icon: '💥', metric: 'totalCrits',
      target: 660, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a3e2_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 76, mode: 'absolute', fige: true,
      label: t => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a3e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 19, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a3e2_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a3e2_reserve', icon: '💰', metric: 'coins',
      target: 1100000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a3e2_esprit', icon: '👻', metric: 'auto:colonie',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Colonies de Familiers' : 'Colonie de Familiers'}` },
    { id: 'a3e2_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
  ],
  // ── Ascension 3 · œuf 3 ──
  [
    { id: 'a3e3_plusC', icon: '💥', metric: 'totalCrits',
      target: 1320, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a3e3_plusB', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 82, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a3e3_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 24, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a3e3_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Fais une Offrande' },
    { id: 'a3e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 55, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a3e3_tap', icon: '✊', metric: 'tapUpgrade:tap5',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Éclat Primordial` },
    { id: 'a3e3_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 21, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a3e3_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Achète une rune' },
  ],
  // ── Ascension 3 · œuf 4 ──
  [
    { id: 'a3e4_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a3e4_tap1b', icon: '🪄', metric: 'tapUpgrade:tap6',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Coeur de Supernova` },
    { id: 'a3e4_reserve', icon: '💰', metric: 'coins',
      target: 84000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a3e4_plusB', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a3e4_gen', icon: '⚙️', metric: 'auto:titan',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Titans Mécaniques' : 'Titan Mécanique'}` },
    { id: 'a3e4_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 89, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a3e4_plusC', icon: '⭐', metric: 'goldenClaimed',
      target: 24, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a3e4_pacte', icon: '🔗', metric: 'tapPower',
      target: 11, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
  ],
  // ── Ascension 3 · œuf 5 ──
  [
    { id: 'a3e5_plusC', icon: '⚙️', metric: 'passiveIncome',
      target: 40000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a3e5_plusC2', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 96, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a3e5_plusB', icon: '🔥', metric: 'maxTapStreak',
      target: 290, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a3e5_gen0b', icon: '👻', metric: 'auto:colonie',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Colonies de Familiers' : 'Colonie de Familiers'}` },
    { id: 'a3e5_plusC3', icon: '💰', metric: 'coins',
      target: 100000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a3e5_plusB2', icon: '✨', metric: 'powerActivated',
      target: 20, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a3e5_gen', icon: '⚙️', metric: 'auto:golem',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Golems de Cristal' : 'Golem de Cristal'}` },
    { id: 'a3e5_plusB3', icon: '⚔️', metric: 'advLevelReached',
      target: 60, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
  ],
  // ── Ascension 3 · œuf 6 ──
  [
    { id: 'a3e6_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 120, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a3e6_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 21, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a3e6_gen1b', icon: '⚙️', metric: 'auto:titan',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Titans Mécaniques' : 'Titan Mécanique'}` },
    { id: 'a3e6_plusC', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a3e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 27, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a3e6_gen2b', icon: '⚙️', metric: 'auto:golem',
      target: 9, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Golems de Cristal' : 'Golem de Cristal'}` },
    { id: 'a3e6_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a3e6_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 92000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
  ],
  // ── Ascension 3 · œuf 7 ──
  [
    { id: 'a3e7_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a3e7_tap', icon: '🪄', metric: 'tapUpgrade:tap5',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Éclat Primordial` },
    { id: 'a3e7_plusC', icon: '⚔️', metric: 'advLevelReached',
      target: 240, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a3e7_plusB', icon: '⭐', metric: 'goldenClaimed',
      target: 30, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a3e7_tap0b', icon: '✊', metric: 'tapUpgrade:tap6',
      target: 3, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Coeur de Supernova` },
    { id: 'a3e7_plusB2', icon: '⚙️', metric: 'passiveIncome',
      target: 160000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a3e7_reserve', icon: '💰', metric: 'coins',
      target: 130000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a3e7_ascend', icon: '🌟', metric: 'ascension',
      target: 4, mode: 'absolute', fige: true, step: 1,
      label: t => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 4 · œuf 1 ──
  [
    { id: 'a4e1_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute', fige: true,
      label: t => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a4e1_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a4e1_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a4e1_crits', icon: '💥', metric: 'totalCrits',
      target: 800, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a4e1_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Monte le Veilleur au niveau ${t}` },
    { id: 'a4e1_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Fais une Offrande' },
    { id: 'a4e1_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 315, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a4e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 10, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
  ],
  // ── Ascension 4 · œuf 2 ──
  [
    { id: 'a4e2_reserve', icon: '💰', metric: 'coins',
      target: 4700000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a4e2_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 104, mode: 'absolute', fige: true,
      label: t => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a4e2_plusB', icon: '🔥', metric: 'maxTapStreak',
      target: 340, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a4e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 20, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a4e2_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Achète une rune' },
    { id: 'a4e2_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 65, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a4e2_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 24, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a4e2_coins', icon: '🪙', metric: 'totalEarned',
      target: 3200000, mode: 'delta', fige: true,
      label: () => 'Obtiens 3,2 millions de pièces' },
  ],
  // ── Ascension 4 · œuf 3 ──
  [
    { id: 'a4e3_plusB', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a4e3_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 47, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a4e3_pacte', icon: '🔗', metric: 'tapPower',
      target: 12, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a4e3_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 22, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a4e3_taps', icon: '👆', metric: 'totalTaps',
      target: 6000, mode: 'absolute', fige: true, minStep: 300,
      label: t => `Atteins ${fmtQ(t)} taps au total` },
    { id: 'a4e3_tap', icon: '✊', metric: 'tapUpgrade:tap7',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Griffe du Vide` },
    { id: 'a4e3_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 33, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a4e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 70, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
  ],
  // ── Ascension 4 · œuf 4 ──
  [
    { id: 'a4e4_plusC', icon: '⭐', metric: 'goldenClaimed',
      target: 37, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a4e4_tap1b', icon: '🪄', metric: 'tapUpgrade:tap8',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Serment Éternel` },
    { id: 'a4e4_reserve', icon: '💰', metric: 'coins',
      target: 350000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a4e4_plusC2', icon: '💥', metric: 'totalCrits',
      target: 1600, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a4e4_gen', icon: '⚙️', metric: 'auto:phenix',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Phénix Renaissants' : 'Phénix Renaissant'}` },
    { id: 'a4e4_plusB', icon: '⚔️', metric: 'advLevelReached',
      target: 75, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a4e4_plusB2', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 112, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a4e4_gen2', icon: '⚙️', metric: 'auto:dragonnet',
      target: 7, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Dragons Miniatures' : 'Dragon Miniature'}` },
  ],
  // ── Ascension 4 · œuf 5 ──
  [
    { id: 'a4e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 150, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a4e5_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', fige: true, step: 5,
      label: t => `Monte une créature au niveau ${t}` },
    { id: 'a4e5_plusC', icon: '💰', metric: 'coins',
      target: 410000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a4e5_gen2b', icon: '⚙️', metric: 'auto:phenix',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Phénix Renaissants' : 'Phénix Renaissant'}` },
    { id: 'a4e5_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 121, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a4e5_plusB', icon: '✨', metric: 'powerActivated',
      target: 23, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a4e5_esprit', icon: '👻', metric: 'auto:golem',
      target: 7, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Golems de Cristal' : 'Golem de Cristal'}` },
    { id: 'a4e5_plusC2', icon: '⚙️', metric: 'passiveIncome',
      target: 150000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
  ],
  // ── Ascension 4 · œuf 6 ──
  [
    { id: 'a4e6_plusC', icon: '⚔️', metric: 'advLevelReached',
      target: 300, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a4e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 41, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a4e6_gen1b', icon: '⚙️', metric: 'auto:dragonnet',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Dragons Miniatures' : 'Dragon Miniature'}` },
    { id: 'a4e6_plusC2', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 131, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a4e6_reserve', icon: '💰', metric: 'coins',
      target: 480000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a4e6_tap', icon: '🪄', metric: 'tapUpgrade:tap7',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Griffe du Vide` },
    { id: 'a4e6_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 320000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a4e6_plusC3', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
  ],
  // ── Ascension 4 · œuf 7 ──
  [
    { id: 'a4e7_plusB', icon: '⭐', metric: 'goldenClaimed',
      target: 45, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a4e7_tap0b', icon: '✊', metric: 'tapUpgrade:tap8',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Serment Éternel` },
    { id: 'a4e7_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a4e7_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 24, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a4e7_gen0b', icon: '👻', metric: 'auto:golem',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Golems de Cristal' : 'Golem de Cristal'}` },
    { id: 'a4e7_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a4e7_plusB2', icon: '⚙️', metric: 'passiveIncome',
      target: 460000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a4e7_ascend', icon: '🌟', metric: 'ascension',
      target: 5, mode: 'absolute', fige: true, step: 1,
      label: t => `Fais ta ${t}e Ascension` },
  ],
  // ── Ascension 5 · œuf 1 ──
  [
    { id: 'a5e1_sanct', icon: '🏛️', metric: 'sanctuaryLevel',
      target: 42, mode: 'absolute', fige: true,
      label: t => `Monte le Sanctuaire au niveau ${t}` },
    { id: 'a5e1_taps', icon: '🗡️', metric: 'battleWon',
      target: 4, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
    { id: 'a5e1_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 370, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a5e1_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 25, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a5e1_veilleur', icon: '🌙', metric: 'veilleurLevel',
      target: 40, mode: 'absolute', fige: true,
      label: t => `Monte le Veilleur au niveau ${t}` },
    { id: 'a5e1_reserve', icon: '💰', metric: 'coins',
      target: 11000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a5e1_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 80, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a5e1_pacte', icon: '🔗', metric: 'tapPower',
      target: 12, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
  ],
  // ── Ascension 5 · œuf 2 ──
  [
    { id: 'a5e2_plusB', icon: '✨', metric: 'powerActivated',
      target: 26, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a5e2_creature', icon: '🐣', metric: 'maxCreatureLevel',
      target: 6, mode: 'absolute', fige: true, step: 5,
      label: t => `Monte une créature au niveau ${t}` },
    { id: 'a5e2_rune', icon: '🔮', metric: 'runeBought',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Achète une rune' },
    { id: 'a5e2_faveur', icon: '🍀', metric: 'critLevel',
      target: 20, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Faveur des Esprits` },
    { id: 'a5e2_etoiles', icon: '🌟', metric: 'threeStarLevel',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Décroche toutes les étoiles sur un niveau d\'Aventure' },
    { id: 'a5e2_golden', icon: '⭐', metric: 'goldenClaimed',
      target: 50, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a5e2_critdmg', icon: '💢', metric: 'critDamageLevel',
      target: 24, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Dégâts critiques` },
    { id: 'a5e2_plusB2', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 5 · œuf 3 ──
  [
    { id: 'a5e3_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 85, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a5e3_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 142, mode: 'absolute', fige: true,
      label: t => `Reste en Transe x2,5 pendant ${t} secondes` },
    { id: 'a5e3_pacte', icon: '🔗', metric: 'tapPower',
      target: 10, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Pacte` },
    { id: 'a5e3_plusB', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a5e3_offrande', icon: '🕯️', metric: 'offering',
      target: 1, mode: 'delta', fige: true,
      label: () => 'Fais une Offrande' },
    { id: 'a5e3_tap', icon: '✊', metric: 'tapUpgrade:tap9',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Fracture du Réel` },
    { id: 'a5e3_crits', icon: '💥', metric: 'totalCrits',
      target: 930, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a5e3_coins', icon: '🪙', metric: 'totalEarned',
      target: 10000000, mode: 'delta', fige: true,
      label: () => 'Obtiens 10 millions de pièces' },
  ],
  // ── Ascension 5 · œuf 4 ──
  [
    { id: 'a5e4_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 450000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a5e4_tap1b', icon: '🪄', metric: 'tapUpgrade:tap10',
      target: 6, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Volonté du Paradoxe` },
    { id: 'a5e4_reserve', icon: '💰', metric: 'coins',
      target: 1800000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a5e4_plusB', icon: '⚔️', metric: 'advLevelReached',
      target: 90, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a5e4_esprit', icon: '👻', metric: 'auto:phenix',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Phénix Renaissants' : 'Phénix Renaissant'}` },
    { id: 'a5e4_plusC', icon: '💥', metric: 'totalCrits',
      target: 1860, mode: 'delta', fige: true,
      label: t => `Obtiens ${t} coups critiques` },
    { id: 'a5e4_taps', icon: '👆', metric: 'totalTaps',
      target: 7000, mode: 'absolute', fige: true, minStep: 300,
      label: t => `Atteins ${fmtQ(t)} taps au total` },
    { id: 'a5e4_gen', icon: '⚙️', metric: 'auto:leviathan',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Léviathans des Abysses' : 'Léviathan des Abysses'}` },
  ],
  // ── Ascension 5 · œuf 5 ──
  [
    { id: 'a5e5_plusB', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 153, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a5e5_plusC', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a5e5_plusC2', icon: '⚙️', metric: 'passiveIncome',
      target: 940000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a5e5_gen', icon: '⚙️', metric: 'auto:gardien',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Gardiens Célestes' : 'Gardien Céleste'}` },
    { id: 'a5e5_plusC3', icon: '⭐', metric: 'goldenClaimed',
      target: 55, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a5e5_adv', icon: '⚔️', metric: 'advLevelReached',
      target: 180, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
    { id: 'a5e5_gen0b', icon: '👻', metric: 'auto:phenix',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Phénix Renaissants' : 'Phénix Renaissant'}` },
    { id: 'a5e5_combats', icon: '🗡️', metric: 'battleWon',
      target: 5, mode: 'delta', fige: true,
      label: t => `Gagne ${t} combats en Aventure` },
  ],
  // ── Ascension 5 · œuf 6 ──
  [
    { id: 'a5e6_gain', icon: '⭐', metric: 'goldenClaimed',
      target: 60, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a5e6_transe', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 166, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a5e6_tap', icon: '🪄', metric: 'tapUpgrade:tap9',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Fracture du Réel` },
    { id: 'a5e6_pouvoirs', icon: '✨', metric: 'powerActivated',
      target: 27, mode: 'delta', fige: true,
      label: t => `Active ${t} fois un pouvoir` },
    { id: 'a5e6_passif', icon: '⚙️', metric: 'passiveIncome',
      target: 1100000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a5e6_gen2b', icon: '⚙️', metric: 'auto:gardien',
      target: 5, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Gardiens Célestes' : 'Gardien Céleste'}` },
    { id: 'a5e6_plusC', icon: '💰', metric: 'coins',
      target: 2200000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a5e6_plusC2', icon: '⚔️', metric: 'advLevelReached',
      target: 360, mode: 'absolute', fige: true,
      label: t => `Termine le ${describeAdventureLevel(t)}` },
  ],
  // ── Ascension 5 · œuf 7 ──
  [
    { id: 'a5e7_plusB', icon: '⚙️', metric: 'passiveIncome',
      target: 1400000, mode: 'absolute', fige: true,
      label: t => `Atteins ${fmtQ(t)} pièces par seconde` },
    { id: 'a5e7_tap0b', icon: '✊', metric: 'tapUpgrade:tap10',
      target: 4, mode: 'delta', fige: true,
      label: t => `Achète ${t} niveau${t > 1 ? 'x' : ''} de Volonté du Paradoxe` },
    { id: 'a5e7_plusC', icon: '🔥', metric: 'maxTranseHoldSec',
      target: 180, mode: 'absolute', fige: true,
      label: t => `Tiens la Transe pendant ${t} secondes` },
    { id: 'a5e7_reserve', icon: '💰', metric: 'coins',
      target: 2500000000, mode: 'absolute', fige: true,
      label: t => `Mets ${qtyQ(t, 'pièces')} de côté` },
    { id: 'a5e7_gen1b', icon: '⚙️', metric: 'auto:leviathan',
      target: 8, mode: 'delta', fige: true,
      label: t => `Achète ${t} ${t > 1 ? 'Léviathans des Abysses' : 'Léviathan des Abysses'}` },
    { id: 'a5e7_plusB2', icon: '⭐', metric: 'goldenClaimed',
      target: 65, mode: 'delta', fige: true,
      label: t => `Touche ${t} fois la cible dorée` },
    { id: 'a5e7_combo', icon: '🔥', metric: 'maxTapStreak',
      target: 400, mode: 'absolute', fige: true,
      label: t => `Enchaîne ${t} taps sans pause` },
    { id: 'a5e7_ascend', icon: '🌟', metric: 'ascension',
      target: 6, mode: 'absolute', fige: true, step: 1,
      label: t => `Fais ta ${t}e Ascension` },
  ],
];
